/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppRoot {}
  interface TodoView {}
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLTodoViewElement extends Components.TodoView, HTMLStencilElement {}
  var HTMLTodoViewElement: {
    prototype: HTMLTodoViewElement;
    new (): HTMLTodoViewElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'todo-view': HTMLTodoViewElement;
  }
}

declare namespace LocalJSX {
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface TodoView extends JSXBase.HTMLAttributes<HTMLTodoViewElement> {}

  interface IntrinsicElements {
    'app-root': AppRoot;
    'todo-view': TodoView;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


